[package]
name = "pingdar_oxide"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.4"
colored = "2.1.0"
prettytable-rs = "0.10.0"
tokio = { version = "1", features = ["full"] }
tokio-wifiscanner = "0.2.*"